# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: build
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install && npm run build

# Stage 2: runtime
FROM node:lts-alpine
WORKDIR /app
# Copy built code
COPY --from=builder /app/dist ./dist
# Copy package files for production install
COPY package.json package-lock.json ./
# Install only production dependencies
RUN npm install --production --ignore-scripts

# Default command to run the MCP server over stdio
ENTRYPOINT ["node", "dist/index.js"]
